version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
