name: Python package

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - name: Checkout gsfpy repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry

      - name: Free disk space on build worker
        run: |
          df -h
          sudo apt-get clean
          sudo apt-get autoclean && sudo apt-get autoremove -y
          df -h

      - name: Run tests
        run: |
          poetry install
          make test-all
